CREATE DATABASE RPG_BCC_B;

CREATE TABLE LOGIN(
    ID_LOGIN INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    TELEFONE INT NOT NULL,
    EMAIL VARCHAR(255),
    NICK VARCHAR(50) NOT NULL UNIQUE,
    SEXO CHAR(1),
    DATA_NASC DATE NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE RACA(
    ID_RACA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    FORCA INT NOT NULL,
    INTELIGENCIA INT NOT NULL,
    FISICO INT NOT NULL,
    VELOCIDADE INT NOT NULL,
    DEFESA INT NOT NULL
);

CREATE TABLE MISSAO(
    ID_MISSAO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    DESCRICAO VARCHAR(55),
    NIVEL INT NOT NULL,
    RECOMPENSA DECIMAL(7,2) NOT NULL
);

CREATE TABLE REGIAO(
    ID_REGIAO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL
);

CREATE TABLE EQUIPAMENTO(
    ID_EQUIPAMENTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(20) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    NIVEL INT NOT NULL
);

CREATE TABLE INIMIGO(
    ID_INIMIGO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30) NOT NULL,
    ID_RACA INT NOT NULL,
    FOREIGN KEY (ID_RACA) REFERENCES RACA(ID_RACA)
);


CREATE TABLE LOJA(
    ID_LOJA INT PRIMARY KEY AUTO_INCREMENT,
    ID_REGIAO INT NOT NULL,
    ID_EQUIPAMENTO INT NOT NULL,
    PRECO DECIMAL(7,2) NOT NULL,
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO),
    FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO(ID_EQUIPAMENTO)
);

CREATE TABLE PERSONAGEM(
    ID_PERSONAGEM INT PRIMARY KEY AUTO_INCREMENT,
    SEXO CHAR(1) NOT NULL,
    ID_LOGIN INT NOT NULL,
    ID_RACA INT NOT NULL,
    ID_REGIAO INT NOT NULL,
    ID_MISSAO INT NOT NULL,
    FOREIGN KEY (ID_LOGIN) REFERENCES LOGIN(ID_LOGIN),
    FOREIGN KEY (ID_RACA) REFERENCES RACA(ID_RACA),
    FOREIGN KEY (ID_REGIAO) REFERENCES REGIAO(ID_REGIAO),
    FOREIGN KEY (ID_MISSAO) REFERENCES MISSAO(ID_MISSAO)
);

CREATE TABLE EQUIPAMENTO_PERSONAGEM(
    ID_PERSONAGEM INT NOT NULL,
    ID_EQUIPAMENTO INT NOT NULL,
    FOREIGN KEY (ID_PERSONAGEM) REFERENCES PERSONAGEM(ID_PERSONAGEM),
    FOREIGN KEY (ID_EQUIPAMENTO) REFERENCES EQUIPAMENTO(ID_EQUIPAMENTO)
);
